### ISSUE TITLE
Final Padding

### ISSUE THREAD

**Issue by dbmcclain** [pmai/sha3#2]
FIPS standard states that SHA3 computes the sponge over the message M||01, and appears to consider bit ordering as running from LSB to MSB in each byte. Then this is padded using the 10*1 padding standard. 

So terminal byte of overall sponged message becomes #x06, not #x01.

(defun pad-message-to-width (message bit-width)
  "Destructively pad the given message to the given bit-width according to 
Keccak padding rules and return the padded message."
  (let ((message-byte-length (length message))
        (width-bytes (truncate bit-width 8)))
    (setq message (adjust-array message (list width-bytes)))
    ;; SHA3 hash standard appends bit 01 to message, then pads with
    ;; 10*1. Bits are ordered from LSB to MSB, so final byte starts as
    ;; #x02 to get 01 appendage, then becomes #x06 after or'ing in the
    ;; first bit of padding
    (setf (aref message message-byte-length) #x06)
    (loop for index from (1+ message-byte-length) below width-bytes
          do (setf (aref message index) #x00)
          finally
       (setf (aref message (1- width-bytes))
             (logior #x80 (aref message (1- width-bytes))))))
  message)

**Comment by pmai** [comment]
Yes, as you noticed I never got around to adjusting the SHA-3 wrappers to match the final FIPS standardized version which appends 01 to the message. I'll commit an updated version that supports the FIPS standardized SHA-3 correctly (and offers the existing behavior as a fallback option) shortly.
