### ISSUE TITLE
Buffer indexing errors in pad-message-to-width

### ISSUE THREAD

**Issue by dbmcclain** [pmai/sha3#3]
As written, the SHA3 digests will sometimes bomb on an invalid array index in the pad-message-to-width. I tracked it down to improper use of the intermediate 200 byte buffer in sha3-update. The issue is that the Keccak sponge will only absorb rate-bytes at a time. So anything in the intermediate buffer beyond that length will be ignored.

The buffer stuffing must be limited to no more than rate-bytes at a time.

(defun sha3-update (state vector &key (start 0) (end (length vector)))
  "Update the given SHA-3 state `state' from`vector', which must be
a simple-array with element-type (unsigned-byte 8), bounded by `start'
and`end', which must be numeric bounding-indices."
  (declare (type sha3-state state) 
           (type (simple-array (unsigned-byte 8) (_)) vector)
           (type fixnum start end)
           (optimize (speed 3) (safety 1) (space 0) (debug 1)))
  (let_ ((keccak-state (sha3-state-state state))
         (buffer (sha3-state-buffer state))
         (buffer-index (sha3-state-buffer-index state))
         (bit-rate (sha3-state-bit-rate state))
         (rate-bytes (truncate bit-rate 8)))
    (declare (type keccak-1600-state keccak-state)
             (type (simple-array (unsigned-byte 8) (200)) buffer)
             (type (integer 0 199) buffer-index)
             (type (integer 0 1600) bit-rate)
             (type (integer 0 200) rate-bytes)
             #._optimize-declaration_)
    ;; Handle potential remaining bytes
    (unless (zerop buffer-index)
      (let ((remainder (- rate-bytes buffer-index))
            (length (- end start)))
        (declare (type fixnum remainder length))
        (replace buffer vector :start1 buffer-index :end1 rate-bytes :start2 start :end2 end)
        ;; Return if still unfilled buffer
        (when (< length remainder)
          (incf (sha3-state-buffer-index state) length)
          (return-from sha3-update))
        ;; Else handle now complete buffer
        (keccak-state-merge-input keccak-state bit-rate buffer 0)
        (keccak-f keccak-state)
        (setf (sha3-state-buffer-index state) 0
              start (+ start remainder))))
    ;; Now handle full blocks, stuff any remainder into buffer
    (loop for block-offset of-type fixnum from start below end by rate-bytes
          do
       (cond
         ((<= (+ block-offset rate-bytes) end)
          (keccak-state-merge-input keccak-state bit-rate vector block-offset)
          (keccak-f keccak-state))
         (t
          (replace buffer vector :start1 0 :start2 block-offset)
          (setf (sha3-state-buffer-index state) (- end block-offset)))))))

**Comment by pmai** [comment]
Indeed the code seems suspect by glancing at it. Do you have an example usage where this bombs out in pad-message-to-width to add as a test-case?

**Comment by dbmcclain** [comment]
Hi Pierre,

Yes, I have 2 of them, offhand… (inside the Zip file, if it makes it across to you. Otherwise, try the .TeX file on its own.

**Comment by pmai** [comment]
Hi,

thanks for the information, however it seems that none of the attachments made it across to me via the github system. Can you attach them via the github web interface?

Thanks, Pierre.

**Comment by dbmcclain** [comment]
Okay, let's give it a try... never done this before...

**Comment by dbmcclain** [comment]
[untitled folder.zip](https://github.com/pmai/sha3/files/470905/untitled.folder.zip)

**Comment by dbmcclain** [comment]
… do you get the impression that I don’t know what I’m doing when it comes to github?

- DM

**Comment by pmai** [comment]
Thanks for the example file, which highlighted the problem. I'll commit a fix shortly.

PS: Just assumed you closed the issue by accident ;).

**Comment by pmai** [comment]
Could you give this version a run and see if it fixes everything?

**Comment by dbmcclain** [comment]
.. and the code now properly reflects the digest of the empty vector by default:

#xA69F73CCA23A9AC5C8B567DC185A756E97C982164FE25859E0D1DCC1475C80A615B2123AF1F5F94C11E3E9402C3AC558F500199D95B6D3E301758586281DCD26

- DM

**Comment by dbmcclain** [comment]
Hi Pierre,

Yes, on my data set the code performs without incident. The test spanned 5845 different (mostly Lisp text) files, but there were a few binary images in there as well. Since the issue was related to file length I can suggest that the code appears to work properly now, but realize that there may be some missing corner cases in my data set. Rather doubtful, but still…

Many thanks for your beautiful efforts!

- DM

**Comment by pmai** [comment]
Hi David,

thanks for the testing and feedback, I've also rerun all existing tests and the sha3 test vectors and everything seems to run ok, so I'll cut a new release.

I have to thank for the great bug reports, and all the best,

Pierre.
